'use strict';

module.exports = {
  kON_CLOSE_CLICK: 'kON_CLOSE_CLICK',
  kON_SHOW_PHONE_CLICK: 'kON_SHOW_PHONE_CLICK',
  kON_BALLOON_VISIBLE: 'kON_BALLOON_VISIBLE',
  kON_BALLOON_HIDDEN: 'kON_BALLOON_HIDDEN'
};
