'use strict';

var kDEFAULT_STORE_PRIORITY = 100000;

var consts = {
  kITEMS_PER_PAGE: [5,10,15,20],
  kPAGES_ON_SCREEN: 3,
  kORGANIZATION_TYPES: [{id:0, title:'Автосервисы'}, {id:1, title:'Автозапчасти'}, {id:2, title:'Все'}],



  kON_ROUTE_DID_CHANGE__ROUTES_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_DATA_CHANGED__WORK_VIEW_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_AUTO_PART_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,
  kON_AUTO_SERVICE_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_DEFAULT_PAGE_SIZE_CHANGED__DEFAULT_PAGE_SIZE_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_REGION__REGION_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_SEARCH_PAGE_SIZE_CHANGED__SEARCH_PAGE_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_AUTO_PART_BY_ID__AUTO_PART_BY_ID_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_AUTOSERVICE_BY_ID__AUTO_SERVICE_BY_ID_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,
  kON_FIXED_TOOLTIP__FIXED_TOOLTIP_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_CATALOG_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_TEST_VALUE__TEST_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_CATALOG__CATALOG_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY
};

module.exports = consts;
