'use strict';

var kDEFAULT_STORE_PRIORITY = 100000;

var consts = {
  kTOP_K: 50,


  kON_RECOMMENDER_DATA_LOADED__RECOMMENDER_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,
  kON_BIN_DATA_CHANGED__RECOMMENDER_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_PAGE_CHANGED__PAGE_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_ROUTE_DID_CHANGE__ROUTES_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_DATA_CHANGED__WORK_VIEW_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,


  kON_AUTO_PART_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,
  kON_AUTO_SERVICE_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_DEFAULT_PAGE_SIZE_CHANGED__DEFAULT_PAGE_SIZE_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY

};

module.exports = consts;
