'use strict';

var kDEFAULT_STORE_PRIORITY = 100000;

var consts = {  
  kON_ROUTE_DID_CHANGE__ROUTES_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_DATA_CHANGED__WORK_VIEW_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_AUTO_PART_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,
  kON_AUTO_SERVICE_SUGGESTION__SUGGESTIONS_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_DEFAULT_PAGE_SIZE_CHANGED__DEFAULT_PAGE_SIZE_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_REGION__REGION_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_SEARCH_PAGE_SIZE_CHANGED__SEARCH_PAGE_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_AUTO_PART_BY_ID__AUTO_PART_BY_ID_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_AUTOSERVICE_BY_ID__AUTO_SERVICE_BY_ID_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY,

  kON_TEST_VALUE__TEST_STORE_PRIORITY: kDEFAULT_STORE_PRIORITY
};

module.exports = consts;
